# Generated by Django 6.0.2 on 2026-02-28 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.IntegerField(default=1)),
                ('balance', models.IntegerField(default=1000)),
                ('debt', models.IntegerField(default=0)),
                ('total_spins', models.IntegerField(default=0)),
                ('total_winnings', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('jackpots_hit', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
