# Generated by Django 6.0.3 on 2026-03-09 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='last_recovery_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
